### ISSUE TITLE
DLLs placed in lib folder not framework folder

### ISSUE THREAD

**Issue by darrencomeau** [VulcanAnalytics/DBTester#31]
[Microsoft documents here](https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks) that DLLs should not be placed into the lib folder directly.
> You should never have a version of the library that is not specific to a framework and placed directly in the root lib folder. (This capability was supported only with packages.config). Doing so would make the library compatible with any target framework and allow it to be installed anywhere, likely resulting in unexpected runtime errors. Adding assemblies in the root folder (such as lib\abc.dll) or subfolders (such as lib\abc\abc.dll) has been deprecated and is ignored when using the PackagesReference format.

**Comment by darrencomeau** [comment]
Actually I was already placing the files in the right place with the build pipeline before packaging

```
 task: CopyFiles@2

  displayName: 'Copy Files to: $(build.artifactstagingdirectory)/lib/net461'

  inputs:

    SourceFolder: 'src/DatabaseTester_net461/bin/x86/Release'



    Contents: 'VulcanAnalytics.DBTester.*'



    TargetFolder: '$(build.artifactstagingdirectory)/lib/net461/'
```
